@url = http://localhost:5000

###
POST {{url}}/api/products
Content-Type: application/json

{
    "name": "Product 2",
    "category": "phones",
    "description": "lorem ipsum",
    "price": 250
}

###
GET {{url}}/api/products?minPrice=150
