@url = http://localhost:5000
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMWM1ZmFkYjU2OTM0MzdlYTYxOTZiMTkzZjM2OTFhYiIsInVuaXF1ZV9uYW1lIjoiZjFjNWZhZGI1NjkzNDM3ZWE2MTk2YjE5M2YzNjkxYWIiLCJqdGkiOiJjZGVlYTBmZC04MmU3LTRlZGYtOTkwYy00ZDBmYzU2MDViMmQiLCJpYXQiOiIxNTYxNDYzOTUzIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJuYmYiOjE1NjE0NjM5NTMsImV4cCI6MTU2MTQ2NzU1MywiaXNzIjoibWFya2V0In0.OeP9gGLK5aNgYxdMrRNCOOYntCpaKKl9QFHTW4G4AG0

###
POST {{url}}/api/products
Content-Type: application/json

{
    "name": "Product 2",
    "category": "phones",
    "description": "lorem ipsum",
    "price": 250
}

###
GET {{url}}/api/products?minPrice=150

###
DELETE {{url}}/api/products/8239144a-d75d-4225-82ab-67e1398a0d71
Authorization: Bearer {{jwt}}

###
POST {{url}}/api/sign-up
Content-Type: application/json

{
    "email": "user1@market.com",
    "password": "secret",
    "role": "user"
}

###
POST {{url}}/api/sign-in
Content-Type: application/json

{
    "email": "admin@market.com",
    "password": "secret"
}

###
GET {{url}}/api/me
Authorization: Bearer {{jwt}}